services:
  - type: web
    name: plant-pal
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plantpal-db
          property: connectionString

databases:
  - name: plantpal-db
    plan: free
